---
title: "SuppFig4"
output: html_document
date: '2024-04-12'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
library(here)
source(here('script', 'utils_cohort_wise.R'))
source(here('script', 'utils_DA.R'))
```

## Load significant taxa - high sensitvity list
```{r}
current_study_res <- read_tsv(here('results_0.1', 'current_study_for_validation.tsv'))
```

## Load profiles
```{r}
metadata <- read.csv(here('results_0.1', 'metadata_with_imputed_updatedage_allInfo.csv'))
all_profiles <- read.csv('../data/species_abundances.csv')

# load all profiles with cre & filtered with 0.1% threshold - unadjusted
all_profiles_with_cpe <- read.csv(here('results_0.1', 'taxonomic_profiles_with_cre_filtered.csv')) %>% 
  dplyr::rename(Index = 'X')

# load combined profiles - batch corrected
# load all profiles with cre & filtered with 0.1% threshold - adjusted
combined_profiles_adj <- read.csv(here('results_0.1', 'taxonomic_profiles_batch_adjusted.csv')) %>% 
  dplyr::rename(Index = 'X')

# get CPE profiles
cpe_profiles <- read.csv(here('data', 'cre_profiles.csv'))
cpe_libids <- names(cpe_profiles)[-1]

# convert SG90 libs to CRE libs
metadata <- metadata %>% 
  mutate(Cohort = case_when(LibraryID %in% cpe_libids ~ 'CPE',
                            TRUE ~ Cohort))
```

# Run cohort wise
```{r}
sg90_association <- get_cohort_profiles(all_profiles_with_cpe, 'SG90', 50)
t2d_association <- get_cohort_profiles(all_profiles_with_cpe, 'T2D', 50)
spmp_association <- get_cohort_profiles(all_profiles_with_cpe, 'SPMP', 15)
cpe_association <- get_cohort_profiles(all_profiles_with_cpe, 'CPE', 30)

sg90_glm <- run_glm(sg90_association)
t2d_glm <- run_glm(t2d_association)
spmp_glm <- run_glm(spmp_association)
cpe_glm <- run_glm(cpe_association)

```

# Run pairwise - on batch corrected data
```{r}
species_thr <- 0.1
hist_filter <- 50

sg90_t2d_association <- get_paired_cohort_profiles(combined_profiles_adj, 'SG90', 'T2D', 50)
sg90_t2d_res <- run_glm(sg90_t2d_association)

sg90_spmp_association <- get_paired_cohort_profiles(combined_profiles_adj, 'SG90', 'SPMP', 50)
sg90_spmp_res <- run_glm(sg90_spmp_association)

spmp_t2d_association <- get_paired_cohort_profiles(combined_profiles_adj, 'T2D', 'SPMP', 50)
spmp_t2d_res <- run_glm(spmp_t2d_association)

cpe_t2d_association <- get_paired_cohort_profiles(combined_profiles_adj, 'T2D', 'CPE', 50)
cpe_t2d_res <- run_glm(cpe_t2d_association)

cpe_spmp_association <- get_paired_cohort_profiles(combined_profiles_adj, 'SPMP', 'CPE', 50)
cpe_spmp_res <- run_glm(cpe_spmp_association)
```


# Plot heatmaps
```{r}
combined_scores <- rbind(
  # single cohort
  sg90_glm %>% mutate(Group = 'SG90') %>% 
    dplyr::select(org_list:padj, Group),
  cpe_glm %>% mutate(Group = 'CPE') %>% 
    dplyr::select(org_list:padj, Group),
  spmp_glm %>% mutate(Group = 'SPMP') %>% 
    dplyr::select(org_list:padj, Group),
  t2d_glm %>% mutate(Group = 'T2D') %>% 
    dplyr::select(org_list:padj, Group),
  
  # pairwise
  sg90_spmp_res %>% mutate(Group = 'SG90\nSPMP') %>% 
    dplyr::select(org_list:padj, Group),
  sg90_t2d_res %>% mutate(Group = 'SG90\nT2D') %>% 
    dplyr::select(org_list:padj, Group),
  
  cpe_spmp_res %>% mutate(Group = 'CPE\nSPMP') %>% 
    dplyr::select(org_list:padj, Group),
  cpe_t2d_res %>% mutate(Group = 'CPE\nT2D') %>% 
    dplyr::select(org_list:padj, Group),
  
  spmp_t2d_res %>% mutate(Group = 'SPMP\nT2D') %>% 
    dplyr::select(org_list:padj, Group)
)

combined_scores <- combined_scores %>% 
    # 0. remove stderror column
    dplyr::select(-stderror) %>% 
    # 1. filter only significant taxa
    #filter(org_list %in% signif_taxa) %>% 
    # 2. filter pval < 0.05
    filter(pval < 0.05) %>% 
    # 3. make long to plot
    pivot_longer(-c('org_list', 'Group')) %>% 
    # 4. remove space, _ from org_list
    mutate(org_list = str_replace_all(org_list, '_', ' '))


# get no of signif taxa per Group
combined_scores %>% 
  filter(name == 'padj', value < 0.05) %>% 
  dplyr::count(Group)

# get beta only
combined_scores_beta <- combined_scores %>% filter(name == 'betaestimate') %>% 
  pivot_wider(names_from = 'Group', values_from = 'value') %>% 
  dplyr::select(-name) %>% 
  pivot_longer(-org_list, names_to = 'Group') %>% 
  mutate(value = as.factor(sign(value)),
         org_list = factor(org_list, levels = rev(sort(unique(combined_scores$org_list)))),
         # Group = factor(Group, levels = c('Original\nNo SPMP',
         #                                  'Original\nWith Old SPMP',
         #                                  'Original\nFIML',
         #                                  'With CPE\nFIML',
         #                                  'Fisher')))
         Group = factor(Group, levels = unique(combined_scores$Group)))

# get significant taxa only >= 1 method
combined_scores_padj <- combined_scores %>% 
  filter(name == 'padj', value < 0.05) %>% 
  dplyr::select(-value)

## get consistency score
score_table <- get_cons_score(combined_scores)
  
  # filter score >= 0.5
score_filter <- score_table %>% 
  filter(Score >= 0.5)

combined_heatmap <- combined_scores_beta %>% 
    # filter taxa w/ 2 out of 3 from previous analysis
    filter(org_list %in% current_study_res$org_list) %>%
    ggplot(aes(x = Group, y = org_list, fill = value)) + 
    geom_tile() + 
    geom_tile(colour = 'black', linewidth = 0.3, show.legend = F, alpha = 0.5) +
    geom_text(data = combined_scores_padj %>% 
                filter(org_list %in% current_study_res$org_list),
              aes(x = Group, y = org_list, label = 'X'), size = 4,
              color = 'white', inherit.aes = F) +
    scale_fill_manual(values = c('blue', 'red'), na.value = 'white',
                      labels = c('Negative', 'Positive', NA),
                      na.translate=F) +
    scale_x_discrete(expand = c(0, 0)) + 
    scale_y_discrete(expand = c(0, 0)) +
    theme_bw() + 
    coord_fixed(ratio=0.265) +
    labs(fill = 'Direction') + 
    # scale_x_discrete(labels = c('SG90 + CPE', 'SG90 + CPE', 'SG90 + CPE', 'SG90 + CPE',
    #                             'All Cohorts', 'All Cohorts', 'All Cohorts', 'All Cohorts',
    #                             'All Cohorts', 'All Cohorts', 'All Cohorts', 'All Cohorts')) +
    theme(axis.text.y = element_text(face = 'italic', size = 9,
                                     margin = margin(r=0),
                                     hjust = 1.05),
          axis.text.x = element_text(size = 10),
          axis.title = element_blank(), 
          plot.background = element_blank(), 
          panel.border = element_blank(), 
          panel.grid = element_blank(), 
          text = element_text(family = 'Arial'), 
          legend.position = 'none', 
          axis.ticks = element_blank(),
          #plot.margin=grid::unit(c(0,0,0,0), "mm"))
          plot.margin=margin(0, 0, 0, 0, 'cm'),
          panel.spacing = unit(0, 'cm'))
  
combined_heatmap

# get wide version
combined_table_sign_mat <- score_table %>% 
  filter(org_list %in% current_study_res$org_list) %>% 
    tibble::column_to_rownames('org_list')

```

## add annotation
```{r}
library(ggpubr)

signif_grob <- rectGrob(x=1, y=1.5, gp=gpar( fill=rainbow(8)[1], alpha=0.5 ))
signif_textgrob <- text_grob(x=1, y=1.5, label='Methods', size=10)

pval_grob <- rectGrob(x=1, y=1.5, gp=gpar( fill=rainbow(8)[2], alpha=0.5 ))
pval_textgrob <- text_grob(x=1, y=1.5, label='Individual Cohort', size=10)

padj_grob <- rectGrob(x=1, y=1.5, gp=gpar( fill=rainbow(8)[3], alpha=0.5 ))
padj_textgrob <- text_grob(x=1, y=1.5, label='Paired Cohorts', size=10)

cohort_pair_heatmap <- combined_heatmap + 
  #coord_cartesian(y = range(seq_along(rownames(combined_table_sign_mat))), clip = 'off') + 
theme(plot.margin = unit(c(0.015, 0.015, 0.07, 0), units="npc")) +
  
  # annotation_custom(grob = signif_grob, xmin = -1, xmax = 2, ymin = -5.5, ymax = -3.5) +
  # annotation_custom(grob = signif_textgrob, xmin = -1, xmax = 2, ymin = -5.5, ymax = -3.5) +
  annotation_custom(grob = pval_grob, xmin=-1.5, xmax=2.5, ymin=-5.5, ymax=-3.5) +
  annotation_custom(grob = pval_textgrob, xmin=-1.5, xmax=2.5, ymin=-5.5, ymax=-3.5) +
  annotation_custom(grob = padj_grob, xmin=2, xmax=7, ymin=-5.5, ymax=-3.5) +
  annotation_custom(grob = padj_textgrob, xmin=2, xmax=7, ymin=-5.5, ymax=-3.5)

cohort_pair_heatmap

```

### plot in editable ppt
```{r}
library(officer)
cohort_pair_dml <- rvg::dml(ggobj = cohort_pair_heatmap)  
# Write the document to a file

officer::read_pptx() %>%
  # add slide ----
  officer::add_slide() %>%
  # specify object and location of object ----
  officer::ph_with(cohort_pair_dml, ph_location(width = 8, height = 6.5)) %>%
  # export slide -----
  base::print(here("figppts", "SuppFig4.pptx")
  )

```


